// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Check if we have valid Supabase credentials (not placeholders)
const isSupabaseConfigured = 
  SUPABASE_URL && 
  SUPABASE_PUBLISHABLE_KEY && 
  SUPABASE_URL !== 'placeholder' && 
  SUPABASE_PUBLISHABLE_KEY !== 'placeholder';

// Create a dummy client if not configured (prevents errors)
const dummyUrl = 'https://placeholder.supabase.co';
const dummyKey = 'placeholder-key';

export const supabase = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : createClient<Database>(dummyUrl, dummyKey, {
      auth: {
        storage: localStorage,
        persistSession: false,
        autoRefreshToken: false,
      }
    });

// Export a flag to check if Supabase is configured
export const isSupabaseReady = isSupabaseConfigured;